### ISSUE TITLE
Error when build ...

### ISSUE THREAD

**Issue by isapi** [neo-project/examples#45]
Start NeoContract converter, Source File: E:\nep17test\bin\Debug\net5.0\FJBC.dll
  Neo.Compiler.MSIL console app v3.0.0.0
EXEC : Convert error : System.Exception: error:System.Void FJBC.NEP17::Mint(System.Numerics.BigInteger)::IL_0047 Call Neo.SmartContract.Framework.IScriptContainer Neo.SmartContract.Framework.Services.System.ExecutionEngine::get_ScriptContainer()(43) [E:\nep17test\FJBC.csproj]
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Neo.Compiler.MSIL.ModuleConverter.TryInsertMethod(NeoModule outModule, MethodDefinition method) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 1175
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCall(OpCode src, NeoMethod to, List`1 methodTokens) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 772
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 805    
     at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in 
C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 277
     --- End of inner exception stack trace ---
     at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in 
C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 281
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 124
     at Neo.Compiler.Program.Compile(Options options, ILogger log) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 165
... ...

**Comment by isapi** [comment]
"C:\Users\erik" ???

**Comment by shargon** [comment]
Could you provide the code?

**Comment by isapi** [comment]
Thanks, @shargon. I'v rebuilt it successfully on VS2019.  It seems VSCode auto-imported the wrong package and caused the error.
